### ISSUE TITLE
채팅 추가 기능 연결

### ISSUE THREAD

**Issue by paengjiwoo** [TO102/to102-FE#11]
# 🚀 Todo

- [ ] 참여하기 버튼 활성화
- [ ] 후기 작성 버튼 활성화
- [ ] 친구 추가 버튼 활성화
